<?php

namespace App\Http\Controllers;

use App\Models\Invoice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class InvoiceController extends Controller
{
    /**
     * List invoices belonging to authenticated user's company.
     */
    /**
     * Display the authenticated company's invoices.
     */
    public function index(Request $request)
    {
        $company = $request->user()->company;

        $invoices = $company->invoices()
            ->with('items')
            ->latest('invoice_date')
            ->latest('id')
            ->get();

        return response()->json([
            'invoices' => $invoices,
        ]);
    }

    /**
     * Create invoice.
     */
    /**
     * Create a new invoice.
     */
    public function store(Request $request)
    {
        // Validate the invoice data sent by the frontend.
        // Invoice number, tax amount, line total, subtotal,
        // and total are intentionally NOT accepted from the frontend.
        $validated = $request->validate([
            'invoice_date' => [
                'required',
                'date',
            ],

            'seller_name' => [
                'required',
                'string',
                'max:255',
            ],

            'customer_name' => [
                'required',
                'string',
                'max:255',
            ],

            'customer_tax_id' => [
                'required',
                'string',
                'max:255',
            ],

            'customer_email' => [
                'required',
                'email',
            ],

            // ISO 4217 currency code.
            // Examples: PHP, USD, EUR, GBP.
            'currency' => [
                'required',
                'string',
                'size:3',
            ],

            'items' => [
                'required',
                'array',
                'min:1',
            ],

            'items.*.description' => [
                'required',
                'string',
                'max:255',
            ],

            'items.*.quantity' => [
                'required',
                'numeric',
                'gt:0',
            ],

            'items.*.unit_price' => [
                'required',
                'numeric',
                'gte:0',
            ],

            // Tax is provided as a percentage.
            // Example: 12 means 12%.
            'items.*.tax_rate' => [
                'required',
                'numeric',
                'gte:0',
                'lte:100',
            ],
        ]);

        // Get the authenticated user's company.
        $company = $request->user()->company;

        // Generate the invoice number on the backend.
        // The user never manually enters this value.
        $invoiceNumber = 'INV-' . now()->format('YmdHis') . '-' .
            strtoupper(\Illuminate\Support\Str::random(4));

        // Create the invoice and its items inside one transaction.
        // If anything fails, the entire invoice is rolled back.
        $invoice = DB::transaction(function () use (
            $company,
            $validated,
            $invoiceNumber
        ) {
            $subtotal = 0;
            $taxAmount = 0;

            // Calculate invoice totals from the submitted items.
            foreach ($validated['items'] as $item) {
                // Calculate the item's subtotal.
                $lineSubtotal =
                    $item['quantity'] * $item['unit_price'];

                // Convert the percentage into an actual tax amount.
                //
                // Example:
                // 20,000 × (12 / 100) = 2,400
                $lineTax =
                    $lineSubtotal * ($item['tax_rate'] / 100);

                $subtotal += $lineSubtotal;
                $taxAmount += $lineTax;
            }

            // Final invoice amount.
            $totalAmount = $subtotal + $taxAmount;

            // Create the invoice.
            $invoice = $company->invoices()->create([
                // Generated by Laravel.
                'invoice_number' => $invoiceNumber,

                'invoice_date' => $validated['invoice_date'],

                'seller_name' => $validated['seller_name'],

                'customer_name' => $validated['customer_name'],

                'customer_tax_id' => $validated['customer_tax_id'],

                'customer_email' => $validated['customer_email'],

                // Always store currency consistently.
                'currency' => strtoupper($validated['currency']),

                // Calculated by the backend.
                'subtotal' => $subtotal,

                'tax_amount' => $taxAmount,

                'total_amount' => $totalAmount,

                // New invoices start as pending.
                'status' => 'PENDING',

                // Unique identifier for this invoice operation.
                'idempotency_key' =>
                (string) \Illuminate\Support\Str::uuid(),
            ]);

            // Create each invoice item.
            foreach ($validated['items'] as $item) {
                // Calculate the item's subtotal.
                $lineSubtotal =
                    $item['quantity'] * $item['unit_price'];

                // Calculate the actual tax amount.
                $lineTax =
                    $lineSubtotal * ($item['tax_rate'] / 100);

                // Calculate the final line total.
                $lineTotal =
                    $lineSubtotal + $lineTax;

                $invoice->items()->create([
                    'description' => $item['description'],

                    'quantity' => $item['quantity'],

                    'unit_price' => $item['unit_price'],

                    // Store the percentage used.
                    'tax_rate' => $item['tax_rate'],

                    // Store the calculated tax amount.
                    'tax_amount' => $lineTax,

                    // Store the calculated line total.
                    'line_total' => $lineTotal,
                ]);
            }

            return $invoice;
        });

        // Return the newly created invoice with its items.
        return response()->json([
            'message' => 'Invoice created successfully.',

            'invoice' => $invoice->load('items'),
        ], 201);
    }


    /**
     * Show one invoice belonging to authenticated user's company.
     */
    public function show(Request $request, Invoice $invoice)
    {
        if ($invoice->company_id !== $request->user()->company_id) {
            abort(404);
        }

        return response()->json(
            $invoice->load([
                'items',
                'processingLogs',
            ])
        );
    }
}
